name: Node.js CI/CD with Docker and GCP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_INSTANCE_NAME: ${{ secrets.GCP_INSTANCE_NAME }}
      GCP_INSTANCE_ZONE: ${{ secrets.GCP_INSTANCE_ZONE }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build --if-present

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ env.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    - name: Prepare Docker image name
      run: |
        PROJECT_NAME_LOWER=$(echo "${{ env.PROJECT_NAME }}" | tr '[:upper:]' '[:lower:]')
        echo "DOCKER_IMAGE_NAME=gcr.io/${{ env.GCP_PROJECT_ID }}/${PROJECT_NAME_LOWER}:${{ github.sha }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }} .
        docker push ${{ env.DOCKER_IMAGE_NAME }}

    - name: Deploy to GCP VM
      run: |
        gcloud compute ssh --zone ${{ env.GCP_INSTANCE_ZONE }} ${{ env.GCP_INSTANCE_NAME }} --command="
        docker pull ${{ env.DOCKER_IMAGE_NAME }} &&
        docker stop ${PROJECT_NAME_LOWER} || true &&
        docker rm ${PROJECT_NAME_LOWER} || true &&
        docker run -d --name ${PROJECT_NAME_LOWER} -p 3000:3000 ${{ env.DOCKER_IMAGE_NAME }}
        " || exit 1